AllCops:
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false
