default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: brasilsincero-api_development

test:
  <<: *default
  database: brasilsincero-api_test

production:
  <<: *default
  database: brasilsincero-api_production
  username: brasilsincero-api
  password: <%= ENV['BRASILSINCERO-API_DATABASE_PASSWORD'] %>
